name: Publish Build
on: push

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Rust and Cargo
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          source $HOME/.cargo/env

      - name: Install Rojo via Cargo
        run: |
          source $HOME/.cargo/env
          cargo install --git https://github.com/rojo-rbx/rojo --branch main rojo

      - name: Install Darklua via Cargo
        run: |
          source $HOME/.cargo/env
          cargo install --git https://github.com/Stefanuk12/darklua --branch hybrid-mode darklua

      - name: Install Wally via Cargo
        run: |
          source $HOME/.cargo/env
          cargo install --git https://github.com/UpliftGames/wally --branch main wally

      - name: Run build script
        run: |
          mkdir build
          chmod +x build.sh
          ./build.sh

      - name: Run bundle script
        run: |
          chmod +x bundle.sh
          ./bundle.sh

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: snapshot
          name: Dev Build
          prerelease: true
          files: |
            ./build/BAGHLibrary.rbxm
            ./build/bundle.lua